language: python
python: 3.6
services:
  - docker

script:
  - docker-compose run web python3 manage.py test

deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
